"""add travels table

Revision ID: 9ed7bf3a6b74
Revises: 784f44dd63e7
Create Date: 2026-05-26 12:05:24.809551

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ed7bf3a6b74'
down_revision: str | Sequence[str] | None = '784f44dd63e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('visited', 'bucketlist')", name='travel_status_check'),
    sa.PrimaryKeyConstraint('id', name=op.f('travel_pkey')),
    sa.UniqueConstraint('country_code', name=op.f('travel_country_code_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel')
    # ### end Alembic commands ###
