"""add_published_column

Revision ID: 032d97aaffb8
Revises: 70de19fc4de0
Create Date: 2026-05-21 14:25:41.751993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "032d97aaffb8"
down_revision: str | Sequence[str] | None = "70de19fc4de0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("published", sa.Boolean(), server_default=sa.text("(true)"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "published")
    # ### end Alembic commands ###
